# Generated by Django 5.2.16 on 2026-09-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_requested_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='activación solicitada'),
        ),
    ]
