# Generated by Django 5.2.17 on 2026-09-24 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_assigned_organizations'),
        ('institutions', '0007_organization_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalSupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('account_reactivation', 'Reactivación de cuenta'), ('close_sessions', 'Cierre de sesiones'), ('access_data', 'Corrección de datos de acceso'), ('technical_error', 'Investigación de error'), ('catalog', 'Corrección o importación de catálogo'), ('other', 'Otro soporte técnico')], max_length=30, verbose_name='tipo')),
                ('subject', models.CharField(max_length=180, verbose_name='asunto')),
                ('description', models.TextField(verbose_name='descripción')),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('in_progress', 'En atención'), ('resolved', 'Resuelta'), ('closed', 'Cerrada')], default='open', max_length=20, verbose_name='estado')),
                ('resolution', models.TextField(blank=True, verbose_name='resolución')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resuelta')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handled_technical_support', to=settings.AUTH_USER_MODEL, verbose_name='atendida por')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='technical_requests', to='institutions.organization', verbose_name='institución relacionada')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_technical_support', to=settings.AUTH_USER_MODEL, verbose_name='solicitada por')),
            ],
            options={
                'verbose_name': 'solicitud técnica',
                'verbose_name_plural': 'solicitudes técnicas',
                'ordering': ('-created_at',),
            },
        ),
    ]
