# Generated by Django 5.2.16 on 2026-09-09 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0005_rename_historical_report_labels'),
        ('institutions', '0006_organization_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdocument',
            name='parent_report',
            field=models.ForeignKey(blank=True, limit_choices_to={'document_type': 'historical_report', 'parent_report__isnull': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='audits.auditdocument', verbose_name='informe anterior relacionado'),
        ),
        migrations.AlterField(
            model_name='auditdocument',
            name='document_type',
            field=models.CharField(choices=[('historical_report', 'Informe anterior'), ('report', 'Informe del expediente'), ('notification', 'Notificación'), ('historical_response', 'Respuesta anterior'), ('historical_evidence', 'Evidencia anterior'), ('historical_extension', 'Prórroga anterior'), ('historical_closure', 'Cierre anterior'), ('other', 'Otro documento')], max_length=30, verbose_name='tipo de documento'),
        ),
        migrations.AddConstraint(
            model_name='auditdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('parent_report__isnull', False)), fields=('parent_report', 'sha256'), name='unique_file_per_historical_report'),
        ),
    ]
