# Generated by Django 5.2.17 on 2026-09-24 14:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_portfolio_history(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Change = apps.get_model("audits", "AuditorPortfolioChange")
    rows = []
    for auditor in User.objects.filter(role="auditor").prefetch_related("assigned_organizations"):
        batch_id = uuid.uuid4()
        for organization in auditor.assigned_organizations.all():
            rows.append(Change(
                auditor_id=auditor.pk,
                organization_id=organization.pk,
                action="assign",
                outcome="applied",
                reason="Asignación existente incorporada al historial.",
                outcome_detail="Migrada desde la cartera vigente.",
                batch_id=batch_id,
                is_bulk=True,
            ))
    Change.objects.bulk_create(rows)


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0006_auditdocument_parent_report_and_more'),
        ('accounts', '0004_user_assigned_organizations'),
        ('institutions', '0007_organization_coordinates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditorPortfolioChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('assign', 'Asignación'), ('unassign', 'Desasignación')], max_length=12, verbose_name='acción')),
                ('outcome', models.CharField(choices=[('applied', 'Aplicada'), ('skipped', 'Omitida'), ('blocked', 'Bloqueada')], max_length=12, verbose_name='resultado')),
                ('reason', models.CharField(max_length=500, verbose_name='motivo')),
                ('outcome_detail', models.CharField(blank=True, max_length=300, verbose_name='detalle del resultado')),
                ('batch_id', models.UUIDField(db_index=True, verbose_name='operación')),
                ('is_bulk', models.BooleanField(default=False, verbose_name='operación masiva')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_changes_made', to=settings.AUTH_USER_MODEL, verbose_name='realizado por')),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_changes', to=settings.AUTH_USER_MODEL, verbose_name='auditor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditor_portfolio_changes', to='institutions.organization', verbose_name='organización')),
            ],
            options={
                'verbose_name': 'cambio de cartera de auditor',
                'verbose_name_plural': 'historial de cartera de auditores',
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['auditor', 'created_at'], name='auditor_portfolio_history'), models.Index(fields=['organization', 'created_at'], name='org_portfolio_history')],
            },
        ),
        migrations.RunPython(seed_portfolio_history, migrations.RunPython.noop),
    ]
