# Generated by Django 5.2.17 on 2026-09-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0007_auditorportfoliochange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorportfoliochange',
            name='reason',
            field=models.CharField(blank=True, max_length=500, verbose_name='motivo'),
        ),
    ]
