# Generated by Django 5.2.17 on 2026-09-24 17:34

import apps.audits.models
import apps.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0008_alter_auditorportfoliochange_reason'),
        ('institutions', '0007_organization_coordinates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=180, verbose_name='asunto')),
                ('category', models.CharField(choices=[('requirements', 'Requisitos y documentación'), ('deadlines', 'Fechas y plazos'), ('findings', 'Observaciones o hallazgos'), ('improvement', 'Plan de mejora'), ('evidence', 'Evidencias presentadas'), ('system', 'Uso del sistema'), ('meeting', 'Solicitud de reunión'), ('other', 'Otra consulta')], max_length=24, verbose_name='categoría')),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=12, verbose_name='prioridad')),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('in_progress', 'En atención'), ('waiting_institution', 'Pendiente de información'), ('answered', 'Respondida'), ('closed', 'Cerrada'), ('reopened', 'Reabierta')], default='open', max_length=24, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='cerrada')),
                ('assigned_auditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_audit_inquiries', to=settings.AUTH_USER_MODEL, verbose_name='auditor responsable')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='audits.auditcase', verbose_name='expediente')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_audit_inquiries', to=settings.AUTH_USER_MODEL, verbose_name='creada por')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_inquiries', to='institutions.organization', verbose_name='organización')),
            ],
            options={
                'verbose_name': 'consulta de auditoría',
                'verbose_name_plural': 'consultas de auditoría',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='AuditInquiryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='enviado')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_inquiry_messages', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='audits.auditinquiry', verbose_name='consulta')),
            ],
            options={
                'verbose_name': 'mensaje de consulta',
                'verbose_name_plural': 'mensajes de consulta',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='AuditInquiryAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.audits.models.inquiry_attachment_upload_path, validators=[apps.core.validators.validate_evidence_file], verbose_name='archivo')),
                ('original_filename', models.CharField(max_length=255, verbose_name='nombre original')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='tamaño')),
                ('sha256', models.CharField(max_length=64, verbose_name='huella SHA-256')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='subido')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='audits.auditinquiry', verbose_name='consulta')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_audit_inquiry_attachments', to=settings.AUTH_USER_MODEL, verbose_name='subido por')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='audits.auditinquirymessage', verbose_name='mensaje')),
            ],
            options={
                'verbose_name': 'archivo de consulta',
                'verbose_name_plural': 'archivos de consulta',
                'ordering': ('uploaded_at',),
            },
        ),
    ]
