from django.urls import path

from . import views
from . import historical_bulk


urlpatterns = [
    path("documentos-historicos/carga-multiple/", historical_bulk.historical_bulk_upload,
         name="historical_bulk_upload"),
    path("centros/<int:organization_pk>/informes-anteriores/carga-multiple/", historical_bulk.historical_bulk_upload,
         name="center_historical_bulk_upload"),
    path("centros/<int:organization_pk>/informes-anteriores/carga-multiple/archivo/", historical_bulk.historical_bulk_file,
         name="historical_bulk_file"),
    path("", views.DashboardView.as_view(), name="dashboard"),
    path("consultas/", views.audit_inquiry_list, name="audit_inquiries"),
    path("consultas/nueva/", views.audit_inquiry_create, name="audit_inquiry_create"),
    path("consultas/<int:pk>/", views.audit_inquiry_detail, name="audit_inquiry_detail"),
    path("consultas/<int:pk>/gestionar/", views.audit_inquiry_manage, name="audit_inquiry_manage"),
    path("consultas/<int:pk>/cerrar/", views.audit_inquiry_close, name="audit_inquiry_close"),
    path("consultas/archivos/<int:pk>/", views.download_audit_inquiry_attachment,
         name="audit_inquiry_attachment"),
    path("mi-historial/", views.institution_history, name="institution_history"),
    path("direccion/", views.DirectorDashboardView.as_view(), name="director_dashboard"),
    path("direccion/accesos/", views.director_access_accounts, name="director_access_accounts"),
    path("direccion/accesos/<int:pk>/suspender/", views.director_suspend_institutional_account, name="director_suspend_institutional_account"),
    path("direccion/alertas/", views.director_alerts, name="director_alerts"),
    path("direccion/actividad/", views.director_activity, name="director_activity"),
    path("direccion/solicitudes-tecnicas/", views.director_technical_requests, name="director_technical_requests"),
    path("direccion/auditores/", views.director_auditor_list, name="director_auditors"),
    path("direccion/auditores/nuevo/", views.director_auditor_create, name="director_auditor_create"),
    path("direccion/auditores/<int:pk>/", views.director_auditor_detail, name="director_auditor_detail"),
    path("direccion/auditores/<int:pk>/editar/", views.director_auditor_edit, name="director_auditor_edit"),
    path("direccion/auditores/<int:pk>/archivar/", views.director_auditor_archive, name="director_auditor_archive"),
    path("direccion/auditores/<int:pk>/organizaciones/<int:organization_pk>/", views.director_auditor_assignment, name="director_auditor_assignment"),
    path("direccion/auditores/<int:pk>/organizaciones/operacion-masiva/", views.director_auditor_bulk_assignment, name="director_auditor_bulk_assignment"),
    path(
        "direccion/estadisticas/",
        views.DirectorStatisticsView.as_view(),
        name="director_statistics",
    ),
    path(
        "direccion/estadisticas/exportar.xlsx",
        views.DirectorStatisticsXlsxView.as_view(),
        name="director_statistics_xlsx",
    ),
    path(
        "direccion/centros-educativos/",
        views.DirectorEducationalCenterListView.as_view(),
        name="director_educational_centers",
    ),
    path(
        "direccion/centros-educativos/<int:pk>/",
        views.DirectorEducationalCenterDetailView.as_view(),
        name="director_educational_center_detail",
    ),
    path(
        "direccion/centros-educativos/<int:pk>/activar/",
        views.director_activate_educational_center,
        name="director_activate_educational_center",
    ),
    path("direccion/decisiones/", views.director_decision_list, name="director_decisions"),
    path(
        "direccion/decisiones/<int:pk>/",
        views.director_decision_detail,
        name="director_decision_detail",
    ),
    path(
        "direccion/expedientes/<int:pk>/reasignar/",
        views.director_reassign_case,
        name="director_reassign_case",
    ),
    path("expedientes/", views.CaseListView.as_view(), name="case_list"),
    path("expedientes/nuevo/", views.case_create, name="case_create"),
    path("expedientes/<int:pk>/", views.case_detail, name="case_detail"),
    path("expedientes/<int:pk>/editar/", views.case_edit, name="case_edit"),
    path("expedientes/<int:pk>/contenido/", views.case_builder, name="case_builder"),
    path(
        "expedientes/<int:pk>/informe/cargar/",
        views.case_report_upload,
        name="case_report_upload",
    ),
    path(
        "expedientes/<int:pk>/importar-recomendaciones/",
        views.case_import_recommendations,
        name="case_import_recommendations",
    ),
    path("expedientes/<int:pk>/publicar/", views.case_publish, name="case_publish"),
    path(
        "expedientes/<int:pk>/solicitar-cierre/",
        views.request_case_closure,
        name="request_case_closure",
    ),
    path("expedientes/<int:pk>/informe/", views.download_report, name="download_report"),
    path(
        "documentos/<int:pk>/descargar/",
        views.download_audit_document,
        name="download_audit_document",
    ),
    path(
        "documentos-historicos/",
        views.historical_document_list,
        name="historical_document_list",
    ),
    path(
        "documentos-historicos/nuevo/",
        views.historical_document_create,
        name="historical_document_create",
    ),
    path("centros/<int:organization_pk>/informes-anteriores/nuevo/",
         views.historical_document_create, name="center_historical_document_create"),
    path("documentos-historicos/<int:document_pk>/documentos/nuevo/",
         views.historical_attachment_create, name="historical_attachment_create"),
    path("documentos-historicos/documentos/<int:pk>/visibilidad/",
         views.historical_document_visibility, name="historical_document_visibility"),
    path(
        "documentos-historicos/<int:pk>/",
        views.historical_document_detail,
        name="historical_document_detail",
    ),
    path(
        "documentos-historicos/<int:document_pk>/recomendaciones/nueva/",
        views.historical_recommendation_create,
        name="historical_recommendation_create",
    ),
    path("expedientes/<int:case_pk>/hallazgos/nuevo/", views.finding_create, name="finding_create"),
    path("hallazgos/<int:pk>/editar/", views.finding_edit, name="finding_edit"),
    path("hallazgos/<int:pk>/eliminar/", views.finding_delete, name="finding_delete"),
    path(
        "hallazgos/<int:finding_pk>/recomendaciones/nueva/",
        views.recommendation_create,
        name="recommendation_create",
    ),
    path("recomendaciones/<int:pk>/editar/", views.recommendation_edit, name="recommendation_edit"),
    path(
        "recomendaciones/<int:pk>/eliminar/",
        views.recommendation_delete,
        name="recommendation_delete",
    ),
    path("recomendaciones/<int:pk>/responder/", views.respond_recommendation, name="respond_recommendation"),
    path(
        "recomendaciones/<int:pk>/prorroga/",
        views.grant_deadline_extension,
        name="grant_deadline_extension",
    ),
    path("respuestas/<int:pk>/revisar/", views.review_response, name="review_response"),
    path("respuestas/<int:pk>/constancia/", views.response_receipt, name="response_receipt"),
    path("evidencias/<int:pk>/descargar/", views.download_evidence, name="download_evidence"),
]
